// <auto-generated />
namespace AutoVentas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class de_autos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(de_autos));
        
        string IMigrationMetadata.Id
        {
            get { return "201604150054257_de_autos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
